name: Deploy site

on:
  push:
    branches:
    - main
  schedule:
     - cron: '0 0 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js 10.x
      uses: actions/setup-node@main
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@main
      with:
        repo-token: ${{ secrets.GH_PAT }}
